# Generated by Django 5.0.7 on 2026-09-09 19:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=30, unique=True, verbose_name='Cédula / Documento')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Área / Departamento')),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('reference_photo', models.ImageField(blank=True, null=True, upload_to='employees/references/')),
                ('face_encoding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('method', models.CharField(choices=[('FACIAL', 'Reconocimiento facial'), ('MANUAL', 'Registro manual')], default='FACIAL', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('capture_photo', models.ImageField(blank=True, null=True, upload_to='attendance/captures/')),
                ('match_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='attendance.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='attendance__employe_63e069_idx'), models.Index(fields=['log_type', 'timestamp'], name='attendance__log_typ_7f402d_idx')],
            },
        ),
    ]
