# Generated by Django 5.0.7 on 2026-09-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sede',
            field=models.CharField(choices=[('CENTRO', 'Centro'), ('NORTE', 'Norte')], default='CENTRO', max_length=10, verbose_name='Sede'),
        ),
    ]
